name: API Regression Tests

on:
  push:
    branches:
      - dev
      - stage
  pull_request:
    branches:
      - dev
      - stage

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Run Tests & Publish Allure Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set Target Environment
        id: select-env
        run: |
          IF_BRANCH="${GITHUB_REF_NAME}"
          if [ "$IF_BRANCH" = "stage" ]; then
            echo "ENV_NAME=stage" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi

      - name: Run RestAssured Tests
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_CREATE: 1
          TESTOMATIO_TITLE: "GitHub Actions CI Run #${{ github.run_number }}"
        run: mvn clean test -Denv=${{ env.ENV_NAME }}
        continue-on-error: true

      - name: Generate Allure Environment Properties
        if: always()
        run: |
          mkdir -p target/allure-results
          echo "Environment=${{ env.ENV_NAME }}" >> target/allure-results/environment.properties
          echo "Java.Version=17" >> target/allure-results/environment.properties
          echo "Branch=${{ github.ref_name }}" >> target/allure-results/environment.properties
          echo "Runner.OS=${{ runner.os }}" >> target/allure-results/environment.properties

      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history